### ISSUE TITLE
Issue on Installation 

### ISSUE THREAD

**Issue by hnooz** [saasscaleup/laravel-n-plus-one-detector#1]
This message in the terminal shows up when I try to install the package 

also, the config file is not published

![Screenshot from 2024-07-10 10-25-41](https://github.com/saasscaleup/laravel-n-plus-one-detector/assets/44949769/5997e957-2207-4ada-8cad-f2da35f147d9)

**Comment by saasscaleup** [comment]
We pushed a fix. Please try to install again and let us know. Thank you so much for your update.

**Comment by saasscaleup** [comment]
We verified the fix few times. Everything is working perfectly. 
<img width="1170" alt="Screenshot 2024-07-10 at 1 10 26" src="https://github.com/saasscaleup/laravel-n-plus-one-detector/assets/100524415/173704c5-ce5b-4e34-b728-c90f66c32246">

**Comment by hnooz** [comment]
It's still not working for me even after I removed the vendor and composer.lock and re-ran composer install.
![Screenshot from 2024-07-10 11-21-39](https://github.com/saasscaleup/laravel-n-plus-one-detector/assets/44949769/a5af90d5-3271-404e-884a-c5a5b967ef9d)

**Comment by saasscaleup** [comment]
Please try again with new Laravel installation. Also share your laravel version.

**Comment by saasscaleup** [comment]
## Here another installation of Laravel. Everything working smoothly 🫶✅ 

<img width="1169" alt="Screenshot 2024-07-10 at 9 22 28" src="https://github.com/saasscaleup/laravel-n-plus-one-detector/assets/100524415/70f9891c-47f6-4804-8c8e-3bae20a289a7">

**Comment by Dansday** [comment]
![image](https://github.com/user-attachments/assets/96fb06c7-5486-48fb-9fc0-da2921f0a0e3)

Same issue here with the installation @saasscaleup

**Comment by Dansday** [comment]
![image](https://github.com/user-attachments/assets/504f34e1-1e9f-40ae-aed4-cedb99f78284)

Try another command still same @saasscaleup

**Comment by saasscaleup** [comment]
Thanks for sharing . Will check it soon and keep you posted @Dansday

**Comment by saasscaleup** [comment]
Ok. We have a solution. @Dansday @Hnooz 

Publish package's config, migration and view files by running below command:

Try this command first

```bash
php artisan vendor:publish --provider="SaasScaleUp\NPlusOneDetector\NPlusOneDetectorServiceProvider"
```

If you are getting this result:

 ```
No publishable resources for tag [].
Publishing complete.
```

Than try to publish the assests one by one:

```bash
php artisan vendor:publish --provider="SaasScaleUp\NPlusOneDetector\NPlusOneDetectorServiceProvider" --tag=config
```

```bash
php artisan vendor:publish --provider="SaasScaleUp\NPlusOneDetector\NPlusOneDetectorServiceProvider" --tag=views
```

```bash
php artisan vendor:publish --provider="SaasScaleUp\NPlusOneDetector\NPlusOneDetectorServiceProvider" --tag=migrations
```
<img width="1155" alt="Screenshot 2024-07-25 at 12 01 44" src="https://github.com/user-attachments/assets/0cb16919-df06-4f7d-8d8c-7a29ba6aabf1">


Let me know if it's working!

**Comment by Dansday** [comment]
![image](https://github.com/user-attachments/assets/a215ba19-f0a5-4050-a0f0-37bb4b3cf2bd)

No luck @saasscaleup

**Comment by saasscaleup** [comment]
Thanks for sharing . Will check this again and keep you posted

**Comment by saasscaleup** [comment]
Hey @Dansday and @Hnooz . Issue got finally resolve. 

This is the command that you need run

```sh
php artisan vendor:publish --provider="Saasscaleup\NPlusOneDetector\NPlusOneDetectorServiceProvider"
```
<img width="1151" alt="Screenshot 2024-08-01 at 21 28 47" src="https://github.com/user-attachments/assets/553847e7-2801-4bff-8a97-da0424057825">


The issue was that we made a mistake with the name of the provider. 
It was this `SaasScaleUp` (not working) 
Instead of this `Saasscaleup` (working)


Let me know if it's working!
